stages:
  - sync
  - deploy

variables:
  API_ENDPOINT: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/repository/
  GH_USER: AndresCidoncha
  GH_REPO: https://${GH_USER}:${GH_TOKEN}@github.com/AndresCidoncha/gh-test

sync:
  stage: sync
  image: ${ECR_DEVTOOLS}/external/alpine:3.14.0
  before_script:
    - apk add --no-cache git
    - git remote set-url github ${GH_REPO}
    - git remote set-url gitlab https://${GITLAB_REPO_USER}:${GITLAB_REPO_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git"
  script:
    - git pull github HEAD:master
    - git push gitlab HEAD:master_gh
    - 'curl --fail --request POST
      --header "PRIVATE-TOKEN: ${GITLAB_TOKEN}"
      --data "source_branch=master_gh&target_branch=master&title=GH%20Sync"
      "${API_ENDPOINT}"'
  only:
    - schedules

deploy:
  stage: deploy
  image: ${ECR_DEVTOOLS}/external/alpine:3.14.0
  before_script:
    - apk add --no-cache git
    - git remote set-url github ${GH_REPO}
  script:
    - git push github HEAD:${CI_COMMIT_REF_NAME}
  except:
    - schedules
