stages:
  - sync
  - deploy

variables:
  API_ENDPOINT: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/repository/merge_requests
  GH_USER: AndresCidoncha
  GH_REPO: https://${GH_USER}:${GH_TOKEN}@github.com/AndresCidoncha/gh-test

sync:
  stage: sync
  image: ${ECR_DEVTOOLS}/external/alpine:3.14.0
  secrets:
    GITLAB_TOKEN:
      vault: gitlab/devo_automation@devo
      file: false
  before_script:
    - apk add --no-cache git curl
    - git config user.email "automation@devo.com"
    - git config user.name "devo_automation"
    - git remote add github ${GH_REPO}
    - git remote add gitlab https://devo_automation:${GITLAB_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git
    - git fetch origin
  script:
    - git checkout master_gh
    - git pull --rebase github master
    - git push gitlab master_gh -f
    - echo $API_ENDPOINT
    - 'curl --fail --request POST
      --header "PRIVATE-TOKEN: ${GITLAB_TOKEN}"
      --data "source_branch=master_gh&target_branch=master&title=GH%20Sync"
      "${API_ENDPOINT}"'
  #only:
  #  - schedules

deploy:
  stage: deploy
  image: ${ECR_DEVTOOLS}/external/alpine:3.14.0
  before_script:
    - apk add --no-cache git
    - git remote add github ${GH_REPO}
  script:
    - git push github HEAD:refs/heads/master
  only:
    - master
  except:
    - schedules
